"""empty message

Revision ID: dcd745233093
Revises: ed4aefdf0832
Create Date: 2021-09-10 19:10:35.846139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd745233093'
down_revision = 'ed4aefdf0832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Servico',
    sa.Column('codigo_servico', sa.Integer(), nullable=False),
    sa.Column('codigo_profissinal', sa.Integer(), nullable=True),
    sa.Column('codigo_cliente', sa.Integer(), nullable=True),
    sa.Column('codigo_ambiente', sa.Integer(), nullable=True),
    sa.Column('codigo_pedido', sa.Integer(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('status_servico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_ambiente'], ['Ambiente.codigo_ambiente'], ),
    sa.ForeignKeyConstraint(['codigo_cliente'], ['Profissional.codigo_profissional'], ),
    sa.ForeignKeyConstraint(['codigo_profissinal'], ['Profissional.codigo_profissional'], ),
    sa.PrimaryKeyConstraint('codigo_servico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Servico')
    # ### end Alembic commands ###
