"""empty message

Revision ID: ed4aefdf0832
Revises: 
Create Date: 2021-08-27 18:50:59.691973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4aefdf0832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ambiente',
    sa.Column('codigo_ambiente', sa.Integer(), nullable=False),
    sa.Column('nome_ambiente', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('codigo_ambiente')
    )
    op.create_table('CategoriaProduto',
    sa.Column('codigo_categoria_produto', sa.Integer(), nullable=False),
    sa.Column('descricao_categoria_produto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('codigo_categoria_produto')
    )
    op.create_table('Cliente',
    sa.Column('codigo_cliente', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=200), nullable=False),
    sa.Column('cep_cliente', sa.String(length=9), nullable=False),
    sa.Column('rua_cliente', sa.String(length=200), nullable=False),
    sa.Column('bairro_cliente', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento_cliente', sa.String(length=10), nullable=False),
    sa.Column('CPF_cliente', sa.String(length=11), nullable=False),
    sa.Column('email_cliente', sa.String(length=200), nullable=False),
    sa.Column('telefone_celular', sa.String(length=23), nullable=False),
    sa.PrimaryKeyConstraint('codigo_cliente')
    )
    op.create_table('FormaPagamento',
    sa.Column('codigo_forma_pagamento', sa.Integer(), nullable=False),
    sa.Column('nome_forma_pagamento', sa.String(length=200), nullable=False),
    sa.Column('descricao_forma_pagamento', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('codigo_forma_pagamento')
    )
    op.create_table('ItemPedido',
    sa.Column('codigo_item_pedido', sa.Integer(), nullable=False),
    sa.Column('codigo_pedido', sa.Integer(), nullable=False),
    sa.Column('qtd_item', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_item_pedido')
    )
    op.create_table('TipoDecoracao',
    sa.Column('codigo_tipo_decoracao', sa.Integer(), nullable=False),
    sa.Column('nome_tipo_decoracao', sa.String(length=200), nullable=False),
    sa.Column('descricao_tipo_decoracao', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('codigo_tipo_decoracao')
    )
    op.create_table('TipoProfissional',
    sa.Column('codigo_tipo_profissional', sa.Integer(), nullable=False),
    sa.Column('nome_tipo_profissional', sa.String(length=200), nullable=False),
    sa.Column('descricao_tipo_profissional', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('codigo_tipo_profissional')
    )
    op.create_table('Pedido',
    sa.Column('codigo_pedido', sa.Integer(), nullable=False),
    sa.Column('data_abertura_pedido', sa.DateTime(), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('situacao_pedido', sa.Integer(), nullable=False),
    sa.Column('codigo_forma_pagamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_forma_pagamento'], ['FormaPagamento.codigo_forma_pagamento'], ),
    sa.PrimaryKeyConstraint('codigo_pedido')
    )
    op.create_table('Produto',
    sa.Column('codigo_produto', sa.Integer(), nullable=False),
    sa.Column('descricao_produto', sa.String(length=100), nullable=False),
    sa.Column('qtd_estoque', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=60), nullable=False),
    sa.Column('material', sa.String(length=60), nullable=False),
    sa.Column('tamanho', sa.Float(), nullable=False),
    sa.Column('valor_unitario_produto', sa.Float(), nullable=False),
    sa.Column('codigo_categoria_produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_categoria_produto'], ['CategoriaProduto.codigo_categoria_produto'], ),
    sa.PrimaryKeyConstraint('codigo_produto')
    )
    op.create_table('Profissional',
    sa.Column('codigo_profissional', sa.Integer(), nullable=False),
    sa.Column('nome_completo_profissional', sa.String(length=200), nullable=False),
    sa.Column('url_foto_profissional', sa.String(length=300), nullable=True),
    sa.Column('telefone_celular_profissional', sa.String(length=23), nullable=False),
    sa.Column('email_profissional', sa.String(length=200), nullable=False),
    sa.Column('reputacao_profissional', sa.Float(), nullable=True),
    sa.Column('codigo_tipo_profissinal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_tipo_profissinal'], ['TipoProfissional.codigo_tipo_profissional'], ),
    sa.PrimaryKeyConstraint('codigo_profissional')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Profissional')
    op.drop_table('Produto')
    op.drop_table('Pedido')
    op.drop_table('TipoProfissional')
    op.drop_table('TipoDecoracao')
    op.drop_table('ItemPedido')
    op.drop_table('FormaPagamento')
    op.drop_table('Cliente')
    op.drop_table('CategoriaProduto')
    op.drop_table('Ambiente')
    # ### end Alembic commands ###
